config/routes.rb
Rails.application.routes.draw do
  get 'settings/new'

  get 'settings/create'

  get 'settings/update'

  get 'settings/edit'

  get 'settings/destroy'

  get 'settings/index'

  get 'settings/show'

  get 'settings' => 'settings#index'

  get 'test/new'

  get 'test/create'

  get 'test/update'

  get 'test/edit'

  get 'test/destroy'

  get 'test/index'

  get 'test/show'

  get "index" => "app#index"

  resources :user_forms

  resources :blogs do
     resources :comments
  end

  resources :authentications

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  get "home" => 'home#index'
  post "home" => 'home#index'
  get "home/index"
  

   root 'home#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  
  attr_accessible :birddate, :content, :name, :picture, :picture_cache, :remove_picture, :remote_picture_url
  mount_uploader :picture, PictureUploader

  #=======================================
  #  self.search
  #=======================================
  def self.search(search)
      Rails.logger.debug( 'hello from search blogs' )
      unless (search.nil? || search.empty?)
	  Rails.logger.debug( 'search != nil and empty' )
        return (Blog.where('`name` LIKE ? OR `content` LIKE ?', "%#{search}%", "%#{search}%"))

      else
          Rails.logger.debug( 'search nill' )
        return (Blog.scoped)

      end
  rescue Exception => error
   return (Blog.all)
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authenticate_user!
  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.search(params[:search]).page(params[:page]).per(2)
      respond_to do |format|
      format.html { # index.html.erb
        if ( request.xhr? )
          render( { :partial => 'blogs/search', :layout => false } )
          return
        end
      }
      format.json { render json: @blogs }
    end
  end
  # GET /blogs/1
  # GET /blogs/1.json
  def show
Rails.logger.debug( 'inside show' )
    #@comments = Comment.all
    @blog = Blog.find(params[:id])
    @comments = @blog.comments.search(params[:searchC])
    @comments = @comments.page(params[:page]).per(3)
    #Comment.where(:blog_id => params[:id])
    #@user_post = User.where({:id => @blog.user_id}).first
    #@user_post = @blog.user
    @ulr_img = @blog.picture_url(:thumb_1).to_s
      respond_to do |format|
      format.html { # show.html.erb
        if ( request.xhr? )
          render( { :partial => 'comments/searchComment', :layout => false } )
          return
        end
      }
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
    #@blog = Blog.new(params[:blog])
    @blog = current_user.blogs.create(params[:blog])
 
    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
      flash[:notice] = "The blog was successfully destroyed"
    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<div id='contenedor'>
<%= form_for @blog, :html => {:multipart => true} do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
        <%= f.label :Picture %><br />
    <%= image_tag (@blog.picture_url(:thumb_1)) if @blog.picture? %><br />
    <%= f.file_field :picture %> 
    <label>or a picture's URL:</label>
    <%= f.text_field :remote_picture_url %> <br />
    <%= f.hidden_field :picture_cache %>
  </div>
  <p>
    <label>
      <%= f.check_box :remove_picture %>
      Remove picture
    </label>
  </p>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/blogs/_search.html.erb
<%= paginate @blogs,:outer_window => 3  %><br />
<div id="contenedor2">
<% @blogs.each do |blog| %>
<hr />
<div class="entrada">
     <h4><%=t '.Post by: ' %><%= blog.user.login%></h4>
     <h4><%=t '.Blog name: ' %><%= blog.name %></h4>
     <%= image_tag blog.picture_url(:thumb_2).to_s %>
     <p><%=t '.Post date: ' %><%= blog.created_at %></p>
     <p><%=t '.Content: ' %><%= blog.content%> </p>
     <p><%= link_to 'Show', blog %> -  <%= link_to 'Edit', edit_blog_path(blog) %> - 
     <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></p>
</div>
<% end %>
<br />
</div>
<br />
<%= paginate @blogs,:outer_window => 3  %><br />

app/views/blogs/edit.html.erb
<div id='contenedor'>
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div id="blogs">
<div id="contenedor">
<%= form_tag( blogs_path, { :method => 'get', :id => 'searchBlogs', :onSubmit => 'return(searchFormHandler( this ));' } ) do -%>
  <h5>
    <%=t '.Search blogs that conteain' %><%= text_field_tag "search", params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </h5>
<%- end -%>
<h1><%=t '.Listing blogs' %></h1>
<div id="results">
<%= render :partial => "blogs/search", :locals => { :blog => @blog } -%>
</div>
<br />
<%= link_to 'New Blog', new_blog_path %> |
<%= link_to "Home", home_path %> 
</div>
</div>

app/views/blogs/index.js.erb
jQuery("#blogs").html("<%= escape_javascript(render("blogs")) %>");

app/views/blogs/new.html.erb
<div id='contenedor'>
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div id='contenedor'>

<p id="notice"><%= notice %></p>

<p>
  <b>Posted by:</b>
  <%= @blog.user.login %>
</p>

<p id='pictureBlog'>
  <b>Picture:</br>
  <% if (@blog.picture.to_s == '/assets//assets/default.jpg_default.jpg') %>
   <%= image_tag @blog.picture_url(:thumb_1).to_s %><br />
  <% else %>
  <%= link_to (@blog.picture_url) do %>
     <%= image_tag @blog.picture_url(:thumb_1).to_s %>
  <% end %>
  <% end %>
</p>

<p>
  <b>Name:</b>
  <%= @blog.name %>
</p>

<p>
  <b>Post date:</b>
  <%= @blog.created_at %>
</p>

<div id='cajacontenido'>
  <h3>Content:</h3>
  <%= @blog.content %>
</div>
<br />
<div >
<%= render :template => "comments/index", :locals => { :blog => @blog, :comments => @comments } %>
</div>
<br />
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %> |
<%= link_to "Home", home_path %>
</div>