config/routes.rb
Rails.application.routes.draw do
  get 'settings/new'

  get 'settings/create'

  get 'settings/update'

  get 'settings/edit'

  get 'settings/destroy'

  get 'settings/index'

  get 'settings/show'

  get 'settings' => 'settings#index'

  get 'test/new'

  get 'test/create'

  get 'test/update'

  get 'test/edit'

  get 'test/destroy'

  get 'test/index'

  get 'test/show'

  get "index" => "app#index"

  resources :user_forms

  resources :blogs do
     resources :comments
  end

  resources :authentications

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  get "home" => 'home#index'
  post "home" => 'home#index'
  get "home/index"
  

   root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog
  attr_accessible :content, :user_id
  
  #=======================================
  #  self.search
  #=======================================
  def self.search(search)
      Rails.logger.debug( 'hello from search comments' )
      unless (search.nil? || search.empty?)
    Rails.logger.debug( 'search != nil and empty in comments' )
        return (where('`content` LIKE ?', "%#{search}%"))

      else
          Rails.logger.debug( 'search nill in comments' )
        return (scoped)

      end
  rescue Exception => error
   return (Blog.all)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 before_filter :authenticate_user!
  # GET /comments
  # GET /comments.json
  def index
    @blog = Blog.find(params[:blog_id])
    @comments = @blog.comments.search(params[:searchC])
    @comments = @comments.page(params[:page]).per(3)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @blog = Blog.find(params[:blog_id])
    @comment = Comment.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
    @blog = Blog.find(params[:blog_id])
  end

  # POST /comments
  # POST /comments.json
  def create
    #@comment = Comment.new(params[:comment])
     @blog = Blog.find(params[:blog_id])
     @comment = @blog.comments.create(params[:comment])
     #@comment = current_user.comments.create(params[:comment])
     @comment.user = current_user
     #@comment.blog_id = @blog.id
 
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @blog, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to blog_path(@comment.blog_id), notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to blog_path( @comment.blog_id) }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@blog, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_searchComment.html.erb
<h6><%= paginate @comments,:outer_window => 3  %></h6>
<%- @comments.each do |comment| -%>
<hr />
  	<div class="entrada">
        <p > <b>Commented by: </b><%= comment.user.login %></p>
        <div id='cajacontenido2' ><p>Post date: <%= comment.created_at %></p>
        Comment: <%= comment.content %></div>
        <p><%= link_to 'Show', blog_comment_path( @blog, comment ) %> -
        <%= link_to 'Edit', edit_blog_comment_path( @blog, comment) %> -
        <%= link_to 'Destroy', blog_comment_path( @blog, comment ), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  	</div>

<%- end -%>
<hr />
<h6><%= paginate @comments,:outer_window => 3  %></h6>

app/views/comments/edit.html.erb
<div id='contenedor'>
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', blog_comment_path( @comment.blog_id, @comment)%> |
<%= link_to 'Back', blog_path( @comment.blog_id) %>
</div>

app/views/comments/index.html.erb
<div id="contenedor3">
<h3>Listing comments</h3>
<%= form_tag( [@blog, @comment], { :method => 'get', :id => 'searchComments', :onSubmit => 'return(searchFormHandler2( this ));' } ) do -%>
  <h5>
    <%= 'Search comments that conteain ' %><%= text_field_tag "searchC", params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </h5>
<%- end -%>
<div id='resultsC'>
<%= render :partial => "comments/searchComment", :locals => { :blog => @blog, :comments => @comments } -%>
</div>
<p><%= link_to 'New Comment', new_blog_comment_path( @blog ) %></p>

app/views/comments/new.html.erb
<div id='contenedor'>
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_path( @blog ) -%>
</div>

app/views/comments/show.html.erb
<div id='contenedor'>


<p id="notice"><%= notice %></p>

<p>
  <h4>User:</h4>
  <%= @comment.user.login %>

  <h4>Blog:</h4>
  <%= @comment.blog_id %>

  <h4>Content:</h4>
  <%= @comment.content %>
</p>


<%= link_to 'Edit', edit_blog_comment_path( @comment.blog_id, @comment) %> |
<%= link_to 'Back', blog_path(@comment.blog_id) %>

</div>