config/routes.rb
Rails.application.routes.draw do
  get 'settings/new'

  get 'settings/create'

  get 'settings/update'

  get 'settings/edit'

  get 'settings/destroy'

  get 'settings/index'

  get 'settings/show'

  get 'settings' => 'settings#index'

  get 'test/new'

  get 'test/create'

  get 'test/update'

  get 'test/edit'

  get 'test/destroy'

  get 'test/index'

  get 'test/show'

  get "index" => "app#index"

  resources :user_forms

  resources :blogs do
     resources :comments
  end

  resources :authentications

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  get "home" => 'home#index'
  post "home" => 'home#index'
  get "home/index"
  

   root 'home#index'

end

app/controllers/user_forms_controller.rb
class UserFormsController < ApplicationController
  # GET /user_forms
  # GET /user_forms.json
  def index
    @user_forms = UserForm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_forms }
    end
  end

  # GET /user_forms/1
  # GET /user_forms/1.json
  def show
    @user_form = UserForm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_form }
    end
  end

  # GET /user_forms/new
  # GET /user_forms/new.json
  def new
    @user_form = UserForm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_form }
    end
  end

  # GET /user_forms/1/edit
  def edit
    @user_form = UserForm.find(params[:id])
  end

  # POST /user_forms
  # POST /user_forms.json
  def create
    @user_form = UserForm.new(params[:user_form])

    respond_to do |format|
      if @user_form.save
        format.html { redirect_to @user_form, notice: 'User form was successfully created.' }
        format.json { render json: @user_form, status: :created, location: @user_form }
      else
        format.html { render action: "new" }
        format.json { render json: @user_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_forms/1
  # PUT /user_forms/1.json
  def update
    @user_form = UserForm.find(params[:id])

    respond_to do |format|
      if @user_form.update_attributes(params[:user_form])
        format.html { redirect_to @user_form, notice: 'User form was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_forms/1
  # DELETE /user_forms/1.json
  def destroy
    @user_form = UserForm.find(params[:id])
    @user_form.destroy

    respond_to do |format|
      format.html { redirect_to user_forms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_forms_helper.rb
module UserFormsHelper
end

app/views/user_forms/_form.html.erb
<%= form_for(@user_form) do |f| %>
  <% if @user_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_form.errors.count, "error") %> prohibited this user_form from being saved:</h2>

      <ul>
      <% @user_form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname %><br />
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br />
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_forms/edit.html.erb
<h1>Editing user_form</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_form %> |
<%= link_to 'Back', user_forms_path %>

app/views/user_forms/index.html.erb
<h1>Listing user_forms</h1>

<table>
  <tr>
    <th>Fname</th>
    <th>Lname</th>
    <th>Birthday</th>
    <th>Country</th>
    <th>State</th>
    <th>City</th>
    <th>Gender</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_forms.each do |user_form| %>
  <tr>
    <td><%= user_form.fname %></td>
    <td><%= user_form.lname %></td>
    <td><%= user_form.birthday %></td>
    <td><%= user_form.country %></td>
    <td><%= user_form.state %></td>
    <td><%= user_form.city %></td>
    <td><%= user_form.gender %></td>
    <td><%= link_to 'Show', user_form %></td>
    <td><%= link_to 'Edit', edit_user_form_path(user_form) %></td>
    <td><%= link_to 'Destroy', user_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User form', new_user_form_path %>

app/views/user_forms/new.html.erb
<h1>New user_form</h1>

<%= render 'form' %>

<%= link_to 'Back', user_forms_path %>

app/views/user_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fname:</b>
  <%= @user_form.fname %>
</p>

<p>
  <b>Lname:</b>
  <%= @user_form.lname %>
</p>

<p>
  <b>Birthday:</b>
  <%= @user_form.birthday %>
</p>

<p>
  <b>Country:</b>
  <%= @user_form.country %>
</p>

<p>
  <b>State:</b>
  <%= @user_form.state %>
</p>

<p>
  <b>City:</b>
  <%= @user_form.city %>
</p>

<p>
  <b>Gender:</b>
  <%= @user_form.gender %>
</p>


<%= link_to 'Edit', edit_user_form_path(@user_form) %> |
<%= link_to 'Back', user_forms_path %>